cask_args appdir: '/Applications'

tap 'caskroom/versions'
tap 'homebrew/bundle'

cask 'xquartz'

brew 'ack'
brew 'coreutils'

brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jpegoptim'
brew 'colordiff'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'wget'
brew 'openssl'
brew 'node'
brew 'unrar'
brew 'wget'
brew 'duti'

cask 'firefox'
cask 'google-chrome'
cask 'adobe-creative-cloud'
cask 'sublime-text3'
cask 'virtualbox'
cask 'vagrant'
cask 'iterm2-beta'
cask 'sequel-pro'
cask 'imageoptim'
cask 'imagealpha'
cask 'xtrafinder'
cask 'alfred'
cask 'karabiner'
cask 'logitech-control-center'

cask 'skype'
cask 'phpstorm'
cask 'intellij-idea-ce'
cask 'steam'
cask 'vlc'
#cask 'qbittorrent'


brew 'dockutil'
brew 'dnsmasq'
brew 'nginx'
brew 'mariadb'
